#!/usr/bin/python

# ./ext2_rm <image> <path>

import subprocess
import sys
import os
import time

if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(-1)

    img = sys.argv[1]
    path = sys.argv[2]

    server = subprocess.Popen(["./ext2kmfs",
                               "../../" + img],
                              cwd="./out/bin/")

    time.sleep(0.1)

    client = subprocess.Popen(["./ext2umfs_rm",
                               path],
                              cwd="./out/util/")
    client.wait()
    server.terminate()

    sys.exit(client.returncode)